export const productData = [
  {
    id: 1,
    fullName: "Rohan Das",
    age: 22,
    designation: "Senior React developer",
    salary: "75,000 (Per month)",
  },
  {
    id: 2,
    fullName: "Vicky Sen",
    age: 25,
    designation: "Senior Python developer",
    salary: "70,000 (Per month)",
  },
  {
    id: 3,
    fullName: "Rohit Rawal",
    age: 20,
    designation: "Junior Python developer",
    salary: "28,000 (Per month)",
  },
  {
    id: 4,
    fullName: "Mohit Suthar",
    age: 20,
    designation: "Junior React developer",
    salary: "30,000 (Per month)",
  },
  {
    id: 5,
    fullName: "Amrendra Dewada",
    age: 23,
    designation: "Senior Flutter developer",
    salary: "60,000 (Per month)",
  },
  {
    id: 6,
    fullName: "Rupa Singh",
    age: 24,
    designation: "Junior PHP developer",
    salary: "15,000 (Per month)",
  },
  {
    id: 7,
    fullName: "Ashvina Rabari",
    age: 22,
    designation: "Junior Flutter developer",
    salary: "20,000 (Per month)",
  },
  {
    id: 8,
    fullName: "Ranjeet Kumar",
    age: 19,
    designation: "Senior Content Manager",
    salary: "30,000 (Per month)",
  },
  {
    id: 9,
    fullName: "Purvi Singh",
    age: 25,
    designation: "MERN Stack developer",
    salary: "60,000 (Per month)",
  },
  {
    id: 10,
    fullName: "Vikash Paliwal",
    age: 23,
    designation: "Senior Python developer",
    salary: "55,000 (Per month)",
  },
];
